# ColorWave - Color analysis and palette extraction
name: ColorWave
priority: 100  # High priority - many waves depend on color info
enabled: true

scope:
  sink: docsummarizer.images
  coordinator: analysis
  atom: Color

triggers:
  requires:
    - signal: identity.width
      condition: "> 0"
  skip_when:
    - signal: wave.skipped.ColorWave

emits:
  on_complete:
    - key: color.dominant_colors
      type: List<DominantColor>
      description: List of dominant colors with names, hex values, and percentages

    - key: color.dominant_1
      type: string
      description: Primary dominant color hex
      confidence_range: [0.8, 1.0]

    - key: color.dominant_2
      type: string
      description: Secondary dominant color hex

    - key: color.dominant_3
      type: string
      description: Tertiary dominant color hex

    - key: color.grid
      type: ColorGrid
      description: Color grid for spatial analysis

    - key: color.grid.cell.*
      type: ColorGridCell
      description: Per-cell color information

    - key: color.mean_saturation
      type: double
      description: Average saturation across image (0-1)

    - key: color.is_grayscale
      type: bool
      description: Whether image is mostly grayscale

    - key: color.tint_type
      type: string
      description: Color tint type (sepia, blue, warm, cool, etc.)

    - key: color.palette
      type: List<string>
      description: Hex color palette

    - key: color.unique_count
      type: int
      description: Estimated unique color count

    - key: color.vibrant
      type: string
      description: Most vibrant/saturated color hex

    - key: color.muted
      type: string
      description: Most muted color hex

  on_failure:
    - color.error

listens:
  required:
    - identity.width
    - identity.height

  optional: []

cache:
  emits:
    - key: image
      type: Image<Rgba32>
      description: Loaded image for downstream waves

config:
  bindings: []  # Always runs

lane:
  name: metadata
  max_concurrency: 8  # Fast, can parallelize

tags:
  - color
  - visual
  - palette
  - foundation
