namespace Mostlylucid.Summarizer.Core.Pipeline;

/// <summary>
/// A chunk of content extracted from any source (document, image, data file).
/// Ready for embedding and indexing.
/// </summary>
public class ContentChunk
{
    /// <summary>
    /// Unique identifier for this chunk.
    /// </summary>
    public required string Id { get; init; }

    /// <summary>
    /// The text content for embedding.
    /// </summary>
    public required string Text { get; init; }

    /// <summary>
    /// Content type/modality.
    /// </summary>
    public required ContentType ContentType { get; init; }

    /// <summary>
    /// Source file path.
    /// </summary>
    public required string SourcePath { get; init; }

    /// <summary>
    /// Position/index within the source.
    /// </summary>
    public int Index { get; init; }

    /// <summary>
    /// Hash of the content for deduplication.
    /// </summary>
    public string? ContentHash { get; init; }

    /// <summary>
    /// Confidence/quality score (0-1).
    /// </summary>
    public double? Confidence { get; init; }

    /// <summary>
    /// Additional chunk-specific metadata.
    /// </summary>
    public Dictionary<string, object?> Metadata { get; init; } = [];
}

/// <summary>
/// Type of content in a chunk.
/// </summary>
public enum ContentType
{
    /// <summary>
    /// Text from a document (PDF, DOCX, MD, etc.)
    /// </summary>
    DocumentText,

    /// <summary>
    /// Text extracted from an image via OCR.
    /// </summary>
    ImageOcr,

    /// <summary>
    /// Caption/description of an image from vision model.
    /// </summary>
    ImageCaption,

    /// <summary>
    /// Data from structured files (CSV, JSON, Excel).
    /// </summary>
    StructuredData,

    /// <summary>
    /// Transcript from audio/video.
    /// </summary>
    Transcript,

    /// <summary>
    /// Summary generated by LLM.
    /// </summary>
    Summary,

    /// <summary>
    /// Entity extracted by GraphRAG.
    /// </summary>
    Entity
}
