namespace Mostlylucid.DocSummarizer.Images.Models;

/// <summary>
/// Raw claims from a vision model (before validation against profile)
/// </summary>
public record ImageClaims
{
    /// <summary>
    /// Caption generated by the vision model
    /// </summary>
    public string? Caption { get; init; }

    /// <summary>
    /// Tags/labels extracted by the vision model
    /// </summary>
    public IReadOnlyList<string> Tags { get; init; } = [];

    /// <summary>
    /// Specific claims made by the model with confidence scores
    /// </summary>
    public IReadOnlyList<ImageClaim> Claims { get; init; } = [];

    /// <summary>
    /// Things the model is uncertain about
    /// </summary>
    public IReadOnlyList<string> Uncertainties { get; init; } = [];

    /// <summary>
    /// Any notes or caveats from the model
    /// </summary>
    public IReadOnlyList<string> Notes { get; init; } = [];
}

/// <summary>
/// A specific claim made by a vision model
/// </summary>
/// <param name="Type">Claim type (e.g., "scene", "color", "object", "text_presence")</param>
/// <param name="Text">The claim text</param>
/// <param name="Confidence">Model confidence (0-1)</param>
public record ImageClaim(string Type, string Text, double Confidence);

/// <summary>
/// Result of validating a claim against the image profile
/// </summary>
public enum ClaimValidationResult
{
    /// <summary>
    /// Claim is supported by measured properties
    /// </summary>
    Supported,

    /// <summary>
    /// Claim is not supported by measured properties
    /// </summary>
    Unsupported,

    /// <summary>
    /// Cannot determine - claim is plausible but unverifiable
    /// </summary>
    Uncertain
}

/// <summary>
/// A claim that has been validated against the image profile
/// </summary>
/// <param name="Original">The original claim from the model</param>
/// <param name="Result">Validation result</param>
/// <param name="Reframed">Reframed text if the claim was downgraded (null if supported as-is)</param>
/// <param name="Evidence">Evidence from the profile that supports or refutes the claim</param>
public record ValidatedClaim(
    ImageClaim Original,
    ClaimValidationResult Result,
    string? Reframed,
    string? Evidence
);
